spring.application.name=theverdict

# Server settings
server.port=8090

## Springboot Security
#spring.security.user.name=admin
#spring.security.user.password=secret123

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://dpg-d054bfbe5dus738tavcg-a.oregon-postgres.render.com/the_verdict_db
spring.datasource.username=the_verdict_db_user
spring.datasource.password=iqM08ThJgcl7WV9rEAGOPE0XSwQTi3lX
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=${JDBC_DATABASE_URL}
#spring.datasource.username=${JDBC_DATABASE_USERNAME}
#spring.datasource.password=${JDBC_DATABASE_PASSWORD}

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Secret Key
jwt.secret=ThisIsASuperSecretKeyWithAtLeast32Characters

# Enable CORS (optional, for frontend communication)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*